/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "TaxTrackWeb": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
    "taxtrack-uat-db-migrate": {
      "name": string
      "type": "sst.aws.Function"
    }
    "taxtrack-uat-postgres-rds": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "taxtrack-uat-power-schedule": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}