export const productionSpec = {
  region: "asia-southeast1",
  domain: "taxgenie.online",
  storage: {
    versioning: true,
    uniformAccess: true,
    publicAccessPrevention: "enforced",
    signedUrlTtlSeconds: 900,
  },
  sql: {
    version: "POSTGRES_17",
    tier: "db-custom-1-3840",
    diskGb: 20,
    retainedBackups: 7,
    pointInTimeRecovery: true,
    deletionProtection: true,
  },
  queue: {
    id: "document-extraction",
    maxAttempts: 5,
    minBackoffSeconds: 10,
    maxBackoffSeconds: 600,
    maxRetrySeconds: 86_400,
    maxConcurrentDispatches: 3,
    dispatchDeadlineSeconds: 1_800,
  },
  web: {
    cpu: "1",
    memory: "1Gi",
    concurrency: 20,
    minInstances: 0,
    maxInstances: 3,
    timeoutSeconds: 300,
    ingress: "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER",
  },
  worker: {
    cpu: "2",
    memory: "4Gi",
    concurrency: 1,
    minInstances: 0,
    maxInstances: 3,
    timeoutSeconds: 1_800,
    claimLeaseSeconds: 600,
    ingress: "INGRESS_TRAFFIC_INTERNAL_ONLY",
  },
  iam: {
    webProjectRoles: ["roles/cloudsql.client", "roles/cloudtasks.enqueuer"],
    workerProjectRoles: ["roles/cloudsql.client"],
    migratorProjectRoles: ["roles/cloudsql.client"],
    taskInvokerRole: "roles/run.invoker",
  },
  featureFlags: {
    merge: false,
    outboundEmail: false,
    purge: false,
  },
  deferredResources: ["merge", "outbound-email", "retention-purge"],
} as const;
